# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: meatchain.cloud
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
        SANS:
          - 127.0.0.1
      - Hostname: orderer2
        SANS:
          - 127.0.0.1

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Farm
    Domain: farm.meatchain.cloud
    EnableNodeOUs: true

    Template:
      Count: 1
      SANS:
        - 127.0.0.1
    Users:
      Count: 1

  - Name: Factory
    Domain: factory.meatchain.cloud
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - 127.0.0.1
    Users:
      Count: 1
