name: Go Tests

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.13
    
    - name: Configure env
      run: go env -w GO111MODULE=auto

    - name: Install dependencies for tests
      run: cd chaincode/pig && go get

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Test
    run: go test -v ./chaincode/pig

