name: Go Tests

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Configure ENV
      run: go mod init ./chaincode/pig

    - name: Build
      run: go build -v ./chaincode/pig

    - name: Test
      run: go test -v ./chaincode/pig
